const fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {createClient}=require('@supabase/supabase-js');
const {chromium}=require(process.env.RICHOZ_PLAYWRIGHT_PATH);
const config=JSON.parse(fs.readFileSync(process.env.RICHOZ_LOCAL_STATUS,'utf8'));
assert.equal(config.API_URL,'http://127.0.0.1:56321');
const actors=JSON.parse(fs.readFileSync('/private/tmp/richoz-lot3a-fixtures.json','utf8'));
const app='http://127.0.0.1:56300',proof='docs/validation-lot-3a';
const original=global.fetch;global.fetch=(u,i)=>{assert.ok([app,config.API_URL].includes(new URL(typeof u==='string'?u:u.url).origin));return original(u,i);};
const ok=r=>{assert.equal(r.error,null,r.error?.message);return r.data;};
const service=createClient(config.API_URL,config.SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
async function db(actor){const d=createClient(config.API_URL,config.ANON_KEY,{auth:{autoRefreshToken:false,persistSession:false}});ok(await d.auth.signInWithPassword(actor));return d;}
let browser;
async function context(actor,mobile=false){const c=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1365,height:960}});await c.route('**/*',r=>[app,config.API_URL].includes(new URL(r.request().url()).origin)?r.continue():r.abort());const p=await c.newPage();await p.goto(app+'/login');await p.locator('input[type=email]').fill(actor.email);await p.locator('input[type=password]').fill(actor.password);await p.getByRole('button',{name:'Se connecter',exact:true}).click();await p.waitForURL(u=>!u.pathname.includes('/login'));return {c,p};}
(async()=>{
 browser=await chromium.launch({headless:true});
 const secretary=await db(actors.secretary),tech=await db(actors.tech);
 const title='Navigateur 3A '+crypto.randomUUID();
 const i=ok(await secretary.from('interventions').insert({title,address:'Adresse fictive',technician_id:actors.tech.id,intervention_type:'depannage',status:'termine'}).select().single());
 let {c,p}=await context(actors.secretary);
 await p.goto(app+'/reports/followup');await p.getByRole('heading',{name:'Suivi des rapports attendus'}).waitFor();
 await p.locator('details').last().locator('summary').click();
 await p.getByLabel('Intervention',{exact:true}).selectOption(i.id);
 await p.getByLabel('Date de référence (heure de Zurich)',{exact:true}).fill('2030-09-15T12:00');
 await p.getByRole('button',{name:'Confirmer l’obligation commune'}).click();
 await p.getByText('Obligation confirmée.',{exact:true}).waitFor();
 await p.getByLabel('Technicien',{exact:true}).selectOption(actors.tech.id);
 await p.getByLabel('État',{exact:true}).selectOption('absent');
 const card=()=>p.locator('li').filter({has:p.getByRole('heading',{name:title,exact:true})});
 await card().getByText('Rapport attendu — absent',{exact:true}).waitFor();
 assert.equal(await card().getByRole('button',{name:'Rappeler',exact:true}).isDisabled(),true);
 await p.getByLabel('Intervalle minimal en minutes').fill('5');
 await card().getByRole('button',{name:'Rappeler',exact:true}).evaluate(b=>{b.click();b.click();});
 await p.getByText('Rappel interne créé.',{exact:true}).waitFor();
 let history=ok(await service.from('report_reminder_history').select('*').eq('intervention_id',i.id));assert.equal(history.length,1);
 await p.screenshot({path:proof+'/desktop.png',fullPage:true});
 await card().getByRole('link',{name:'Ouvrir l’intervention'}).click();
 await p.waitForURL(u=>u.pathname==='/calendar' && u.searchParams.get('intervention')===i.id);await p.getByText(title,{exact:true}).first().waitFor();
 console.log('PASS browser desktop: explicit confirmation, filters, manual double click, exact intervention link and persisted notification');
 await p.goto(app+'/reports/followup');await p.getByLabel('Technicien',{exact:true}).selectOption(actors.tech.id);await p.getByLabel('État',{exact:true}).selectOption('submitted');await p.getByText('Aucun élément pour ces filtres.').waitFor();
 let release, signal;const intercepted=new Promise(resolve=>{signal=resolve;});await p.route('**/rest/v1/rpc/get_report_followup',async r=>{await new Promise(resolve=>{release=resolve;signal();});await r.continue();});await p.reload();await intercepted;await p.getByText('Chargement du suivi…',{exact:true}).waitFor();release();await p.getByRole('heading',{name:'Suivi des rapports attendus'}).waitFor();await p.unroute('**/rest/v1/rpc/get_report_followup');
 await p.route('**/rest/v1/rpc/get_report_followup',r=>r.abort());await p.reload();await p.getByText('Suivi inaccessible.',{exact:false}).waitFor();await p.unroute('**/rest/v1/rpc/get_report_followup');await p.getByRole('button',{name:'Réessayer',exact:true}).click();await p.getByRole('heading',{name:'Suivi des rapports attendus'}).waitFor();
 console.log('PASS browser loading/empty/error/retry states');await c.close();
 // Returned report routes keep exact ID + existing feedback on the actual form.
 const returned=ok(await secretary.from('interventions').insert({title:'Correction navigateur 3A '+crypto.randomUUID(),address:'Adresse fictive',technician_id:actors.tech.id,intervention_type:'depannage',status:'en_cours'}).select().single());
 const r=ok(await tech.from('reports').insert({intervention_id:returned.id,technician_id:actors.tech.id,status:'submitted',revision_requested:false,text_content:'Texte fictif'}).select().single());
 ok(await secretary.from('reports').update({status:'rejected',revision_requested:true,revision_message:'Retour navigateur fictif : préciser le travail.'}).eq('id',r.id));
 ok(await secretary.rpc('remind_report',{p_intervention:returned.id,p_interval_seconds:60,p_expected:null}));
 ({c,p}=await context(actors.tech,true));await p.goto(app+'/technician/notifications');
 const link=p.locator(`a[href="/technician/report/${returned.id}?report_id=${r.id}"]`);await link.waitFor();await link.click();
 await p.getByText('Retour navigateur fictif : préciser le travail.',{exact:true}).waitFor();await p.screenshot({path:proof+'/mobile-correction.png',fullPage:true});
 await p.goto(app+'/reports/followup');await p.getByText('Suivi inaccessible.',{exact:false}).waitFor();assert.equal(await p.getByRole('heading',{name:title,exact:true}).count(),0);
 console.log('PASS browser technician: correction notification exact report/comment and staff follow-up denied');await c.close();
 ({c,p}=await context(actors.secretary,true));await p.goto(app+'/reports/followup');await p.getByLabel('Technicien',{exact:true}).selectOption(actors.tech.id);await p.getByLabel('État',{exact:true}).selectOption('correction');
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:proof+'/mobile-followup.png',fullPage:true});await p.getByRole('heading',{name:returned.title,exact:true}).scrollIntoViewIfNeeded();await p.screenshot({path:proof+'/mobile-followup-card.png'});await c.close();
 console.log('PASS browser mobile: follow-up navigation, filters and no horizontal document overflow');
 for(const headers of [{},{authorization:'Bearer invalid'}])assert.equal((await fetch(app+'/api/cron/report-reminders',{method:'POST',headers,body:'{}'})).status,401);
 assert.equal((await fetch(app+'/api/cron/report-reminders',{method:'POST',headers:{authorization:'Bearer local-fictitious-lot3a-only'},body:JSON.stringify({simulation:false})})).status,409);
 const beforeSimulation=ok(await service.from('report_reminder_history').select('id')).length;
 const simulation=await fetch(app+'/api/cron/report-reminders',{method:'POST',headers:{authorization:'Bearer local-fictitious-lot3a-only'},body:JSON.stringify({simulation:true})});
 assert.equal(simulation.status,200);const simulated=await simulation.json();assert.equal(simulated.simulation,true);assert.ok(Array.isArray(simulated.obligations));assert.ok(Array.isArray(simulated.results));
 assert.equal(ok(await service.from('report_reminder_history').select('id')).length,beforeSimulation);
 console.log('PASS HTTP automatic entry: unauthorized rejected; execution disabled; authorized simulation without writes');
 await browser.close();
})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=1;});
